##　PLA by data https://www.csie.ntu.edu.tw/~htlin/mooc/datasets/mlfound_math/hw1_15_train.dat

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_table("https://www.csie.ntu.edu.tw/~htlin/mooc/datasets/mlfound_math/hw1_15_train.dat", header=None, names=["X", "y"])

In [4]:
data.head()    ## x是四個維度的點  y是 +/- 1的值

X  y
0   0.97681 0.10723 0.64385 0.29556  1
1    0.67194 0.2418 0.83075 0.42741  1
2   0.20619 0.23321 0.81004 0.98691  1
3  0.51583 0.055814 0.92274 0.75797  1
4   0.70893 0.10836 0.33951 0.77058  1

In [5]:
type(data)

pandas.core.frame.DataFrame

In [6]:
## X是string......
data.X.loc[0]

'0.97681 0.10723 0.64385 0.29556'

In [7]:
X = pd.DataFrame(data.X.str.split(' ',3).tolist(), columns = ['x1','x2','x3','x4'], dtype=float)
x0 = pd.DataFrame(np.ones([len(X), 1]), columns=["x0"])
X = pd.concat([x0, X], axis=1)
y = data.y
X.head()

x0       x1        x2       x3       x4
0  1.0  0.97681  0.107230  0.64385  0.29556
1  1.0  0.67194  0.241800  0.83075  0.42741
2  1.0  0.20619  0.233210  0.81004  0.98691
3  1.0  0.51583  0.055814  0.92274  0.75797
4  1.0  0.70893  0.108360  0.33951  0.77058

In [8]:
## enumerate 有點像對 columns 點名 ；若是array 像下面這樣 就是對 array 點名 
for i, x in enumerate(np.array(X)):
    if i < 5:
        print(i, x)

0 [ 1.       0.97681  0.10723  0.64385  0.29556]
1 [ 1.       0.67194  0.2418   0.83075  0.42741]
2 [ 1.       0.20619  0.23321  0.81004  0.98691]
3 [ 1.        0.51583   0.055814  0.92274   0.75797 ]
4 [ 1.       0.70893  0.10836  0.33951  0.77058]


In [9]:
np.floor(np.random.rand(5)*400)

array([ 149.,  152.,  166.,  337.,  187.])

In [193]:
## perceptron algorithm  Q 15

# X = np.array([
#     [-2,4,-1],
#     [4,1,-1],
#     [1, 6, -1],
#     [2, 4, -1],
#     [6, 2, -1],

# ])

#y = np.array([-1,-1,1,1,1])

def perceptron(X, Y):
    w = np.zeros(len(X[0]))
    eta = 1
    cnt = 0
    for i, x in enumerate(X):
        if (np.dot(X[i], w)*Y[i]) <= 0: ## 有錯發生，進行更新
#                 print(" i = {}".format(i))
            cnt = cnt + 1
            w = w + eta*X[i]*Y[i]
    print("count: {}".format(cnt))
    return w

w = perceptron(np.array(X),np.array(y))
print(w)

count: 37
[-3.         2.2176136 -1.002694   2.873445   3.6551355]


In [11]:
## 這次要使用 random 的 cycle 去跑 X (記得 y 也要一起改順序)
cycle = np.array(np.arange(len(X)))
np.random.shuffle(cycle)
cycle

array([232, 129,  68, 114, 388, 376, 253, 238, 330, 217,  82, 332, 230,
        39, 223, 159,  52,  77,  32, 153, 160, 109, 392, 270, 258,  84,
       224,  12, 273, 122, 115, 169, 243,  73, 227,  24,   1, 291,  60,
        67, 288, 234, 256, 205, 128,  71, 347,  40, 394, 172, 197, 396,
       112, 187, 391,  93, 262, 317, 150, 101, 335, 385,  81, 337, 206,
        11, 185, 275,  31,  34,  94, 175, 314, 398, 143,  49, 233, 231,
       284,  90, 325,  45, 174, 248,   0, 130, 389, 352,  99, 346, 383,
       235, 240,  88, 280, 303, 137, 294, 156, 300, 201,   6,  30, 311,
       269, 290,  22, 210, 329, 305, 165, 244, 261, 272, 372,  14, 118,
       166, 343, 313, 277, 213, 334,  69, 327,  63, 242, 360,  92, 319,
       283,  91, 167, 111, 162, 225, 102, 268,  17,  44,   8,  97, 359,
       354, 351, 184, 357, 306, 204,  53, 193, 126,  59, 302, 229, 371,
       353, 127,  70,  62, 190, 328, 117, 339, 257, 173, 386, 131, 207,
       209, 286,  27, 358, 105, 263, 179, 145, 279, 259, 331, 32

In [194]:
## 這次要使用 random 的 cycle，然後跑2000次看平均結果要update幾次  (Q 16)
def perceptron_random(X, Y):
    w = np.zeros(len(X[0]))
    eta = 1
    cnt = 0
    cycle = np.array(np.arange(len(X))) # 做 random cycle
    np.random.shuffle(cycle)
    for i, x in enumerate(X[cycle]):
        if (np.dot(X[cycle][i], w)*Y[cycle][i]) <= 0:
            #print("t = {}, i = {}".format(t, i))
            cnt = cnt + 1
            w = w + eta*X[cycle][i]*Y[cycle][i]
#     print(cnt)
    return cnt

cnt_sum = 0
for i in range(2000):
    cnt = perceptron_random(np.array(X),np.array(y))
    cnt_sum = cnt_sum + cnt
print(cnt_sum/2000)

34.4905


In [195]:
## 這次除了要使用 random 的 cycle，還要更改 learning rate    (Q 17)
def perceptron_random(X, Y, eta):
    w = np.zeros(len(X[0]))
    eta = eta
    cnt = 0
    cycle = np.array(np.arange(len(X))) # 做 random cycle
    np.random.shuffle(cycle)
    for i, x in enumerate(X[cycle]):
        if (np.dot(X[cycle][i], w)*Y[cycle][i]) <= 0:
            #print("t = {}, i = {}".format(t, i))
            cnt = cnt + 1
            w = w + eta*X[cycle][i]*Y[cycle][i]
    #print(cnt)
    return cnt

for i in range(2000):
    cnt = perceptron_random(np.array(X),np.array(y), 0.5)
    cnt_sum = cnt_sum + cnt
print(cnt_sum/2000)

68.804


## 進行 pocket algorithm
###### Train : https://www.csie.ntu.edu.tw/~htlin/mooc/datasets/mlfound_math/hw1_18_train.dat
###### Test  : https://www.csie.ntu.edu.tw/~htlin/mooc/datasets/mlfound_math/hw1_18_test.dat


In [19]:
train = pd.read_table("https://www.csie.ntu.edu.tw/~htlin/mooc/datasets/mlfound_math/hw1_18_train.dat", header=None, names=["X", "y"])
test = pd.read_table("https://www.csie.ntu.edu.tw/~htlin/mooc/datasets/mlfound_math/hw1_18_test.dat", header=None, names=["X", "y"])

In [45]:
X_train = pd.DataFrame(train.X.str.split(' ',3).tolist(), columns = ['x1','x2','x3','x4'], dtype=float)
x0 = pd.DataFrame(np.ones([len(X_train), 1]), columns=["x0"])
X_train = pd.concat([x0, X_train], axis=1)
Y_train = train.y
X_train.head()

x0       x1        x2        x3        x4
0  1.0  0.94544  0.428420  0.798330  0.162440
1  1.0  0.85365  0.084168  0.568200  0.492210
2  1.0  0.17095  0.821270  0.984440  0.514860
3  1.0  0.51412  0.921240  0.423230  0.097934
4  1.0  0.28147  0.714340  0.075309  0.911600

In [44]:
X_test = pd.DataFrame(test.X.str.split(' ',3).tolist(), columns = ['x1','x2','x3','x4'], dtype=float)
x0 = pd.DataFrame(np.ones([len(X_test), 1]), columns=["x0"])
X_test = pd.concat([x0, X_test], axis=1)
Y_test = test.y
X_test.head()

x0        x1       x2        x3        x4
0  1.0  0.629260  0.32783  0.010417  0.731020
1  1.0  0.323680  0.61439  0.420970  0.025626
2  1.0  0.159680  0.83346  0.975150  0.327620
3  1.0  0.023526  0.30292  0.014961  0.922880
4  1.0  0.458040  0.74520  0.834060  0.549320

In [188]:
## 先寫一個 error rate 計算 (1. pocket更新需要 2. test set 需要)
def error_rate(w, X, Y):
    error = 0
    for i, x in enumerate(X):
        if (np.dot(X[i], w)*Y[i]) <= 0:
            error = error + 1
    return error/len(X)

In [189]:
def perceptron_pocket(X, Y):
    w = np.zeros(len(X[0]))
    eta = 1
    update = 0  ## update 50次
    update_times = 50
    error = error_rate(w, X, Y)
    cycle = np.array(np.arange(len(X))) # 做 random cycle
    np.random.shuffle(cycle)
    for i, x in enumerate(X[cycle]):
        #print(i)
        if (np.dot(w, X[cycle][i])*Y[cycle][i] <=0):
            w = w + eta*X[cycle][i]*Y[cycle][i]
            error_temp = error_rate(w, X[cycle], Y[cycle])
            #print(error_temp)
            if error_temp < error: ## 如果error較低，就取代舊的線
                #print(i)
#                 print("Old error: {}".format(error))
#                 print("New error: {}".format(error_temp))
                error = error_temp
                update = update + 1
                #print("update: {}".format(update))
                #print("w: {}".format(w))
                #print("============="*5)
            if update == update_times:
                return w
#     print("update: {}".format(update))
    return w

In [191]:
perceptron_pocket(np.array(X_train), np.array(Y_train))

array([ 2.       , -3.589644 , -2.7820195, -1.792106 ,  3.0713667])

In [171]:
## Use test set for verification  (Q 18)
error_sum = 0
for i in range(2000):
    w = perceptron_pocket(np.array(X_train), np.array(Y_train))
    error = error_rate(w, np.array(X_test), np.array(Y_test))
    error_sum = error_sum + error
print("iterated error rate: {}".format(error_sum/2000))

iterated error rate: 0.23245799999999997


In [179]:
## 用 PLA updates 50次，取代pocket updates 50次的結果
def perceptron_random_50update(X, Y, eta=1, update=50):
    w = np.zeros(len(X[0]))
    eta = eta
    cnt = 0
    cycle = np.array(np.arange(len(X))) # 做 random cycle
    np.random.shuffle(cycle)
    for i, x in enumerate(X[cycle]):
        if (np.dot(X[cycle][i], w)*Y[cycle][i]) <= 0:
            cnt = cnt + 1
            w = w + eta*X[cycle][i]*Y[cycle][i]
        if cnt == update:
            return w

In [182]:
error_sum = 0
for i in range(2000):
    w = perceptron_random_50update(np.array(X_train), np.array(Y_train))
    error = error_rate(w, np.array(X_test), np.array(Y_test))
    error_sum = error_sum + error
print("iterated error rate: {}".format(error_sum/2000))

iterated error rate: 0.3631099999999999


In [183]:
## Final, 100 updates instead of 50, and verify the performance of POCKET
def perceptron_pocket(X, Y, update_times = 100):
    w = np.zeros(len(X[0]))
    eta = 1
    update = 0
    update_times = update_times
    error = error_rate(w, X, Y)
    cycle = np.array(np.arange(len(X))) # 做 random cycle
    np.random.shuffle(cycle)
    for i, x in enumerate(X[cycle]):
        if (np.dot(w, X[cycle][i])*Y[cycle][i] <=0):
            w = w + eta*X[cycle][i]*Y[cycle][i]
            error_temp = error_rate(w, X[cycle], Y[cycle])
            #print(error_temp)
            if error_temp < error: ## 如果error較低，就取代舊的線
                error = error_temp
                update = update + 1
            if update == update_times:
                return w
    return w

## Use test set for verification
error_sum = 0
for i in range(2000):
    w = perceptron_pocket(np.array(X_train), np.array(Y_train))
    error = error_rate(w, np.array(X_test), np.array(Y_test))
    error_sum = error_sum + error
print("iterated error rate: {}".format(error_sum/2000))

iterated error rate: 0.23459900000000003
